name: Test build kernel m21 (aosp)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device: [m21]
        varient: [no-ksu]
    name: "ðŸš§ Build for ${{matrix.device}} ${{matrix.varient}}"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update
          bash <(curl https://gist.githubusercontent.com/roynatech2544/0feeeb35a6d1782b186990ff2a0b3657/raw/b170134a94dac3594df506716bc7b802add2724b/setup.sh)
          sudo apt install bison flex libssl-dev
          cp local.config.sample local.config
          echo "OBJ=arch/arm64/boot/Image" >> local.config

      - name: Run build
        run: |
          export DEVICE=${{matrix.device}}
          DEVICE=${{matrix.device}} bash build_kernel.sh ${{matrix.varient}}
          cd scripts/packaging
          TIME="$(date "+%Y%m%d")"
          mv Grass*.zip Grass-AOSP-${{matrix.device}}_${{matrix.varient}}_${TIME}.zip

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: GrassKernel_aosp_${{matrix.device}}_${{matrix.varient}}.zip
          path: scripts/packaging/Grass*

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: scripts/packaging/Grass*.zip
          message: "Grass Build (aosp) For ${{matrix.device}} ${{matrix.varient}} Completed"